name: aplicacion_ac
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-313.0.dev <4.0.0'

dependencies:
  flutter:
    
    sdk: flutter
  pdf: ^3.10.1
  path: ^1.8.0
  sqflite: ^2.0.0+3
  
  path_provider: ^2.0.14
  numberpicker: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0+3
  flutter_launcher_icons: "^0.13.1"
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo4.png"


flutter:
  uses-material-design: true

  assets: 
    - assets/