name: aplicacion_ac
description: A new Flutter project.
publish_to: 'none'
version: 0.1.3

environment:
  sdk: '>=3.0.0-313.0.dev <4.0.0'

dependencies:
  flutter:
    
    sdk: flutter
  pdf: ^3.10.1
  path: ^1.8.0
  sqflite: ^2.0.0+3
  
  
  numberpicker: ^2.1.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  lecle_downloads_path_provider: ^0.0.2+2
  downloads_path_provider_28: ^0.1.2
  pubspec_generator: ^3.0.1
  build_runner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0+3
  flutter_launcher_icons: "^0.13.1"
  integration_test:
    sdk: flutter
  shelf_static: ^1.1.2
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo4.png"


flutter:
  uses-material-design: true
  
  assets: 
    - assets/